"""ASS (Advanced SubStation Alpha) exporter with per-word karaoke timing.

One Dialogue line per segment; each word is prefixed with a ``{\\k<cs>}``
karaoke tag carrying its duration in centiseconds. Plays with word-by-word
highlight in VLC / ffplay / Premiere / Resolve via libass.

CRITICAL — ASS colour byte order is reversed from hex RGB:
``&HAABBGGRR`` (alpha, then BLUE, GREEN, RED). The brand orange #D4952A
therefore becomes ``&H002A95D4`` (R=D4, G=95, B=2A, alpha 00 = opaque).
"""

from backend.models.schemas import Segment, TranscriptionResult

# Colours in &HAABBGGRR order (see module docstring).
PRIMARY_COLOUR = "&H00FFFFFF"    # white text
SECONDARY_COLOUR = "&H002A95D4"  # brand orange #D4952A — karaoke pre-highlight
OUTLINE_COLOUR = "&H00000000"    # black outline
BACK_COLOUR = "&H00000000"       # black shadow

_HEADER = f"""[Script Info]
; Script generated by CapForge
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,72,{PRIMARY_COLOUR},{SECONDARY_COLOUR},{OUTLINE_COLOUR},{BACK_COLOUR},0,0,0,0,100,100,0,0,1,3,0,2,60,60,60,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"""


def _cs(seconds: float) -> int:
    """Convert seconds to integer centiseconds."""
    return int(round(seconds * 100))


def _fmt(seconds: float) -> str:
    """Format seconds as ASS ``H:MM:SS.cc`` (centiseconds, single-digit hours)."""
    total_cs = _cs(seconds)
    h = total_cs // 360000
    m = (total_cs % 360000) // 6000
    s = (total_cs % 6000) // 100
    cs = total_cs % 100
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def _escape(text: str) -> str:
    """Escape ASS-special sequences.

    ``{``/``}`` would open/close an override block — conventionally replaced
    with parentheses. Literal newlines become ASS line breaks (``\\N``).
    """
    return (
        text.replace("{", "(")
        .replace("}", ")")
        .replace("\r\n", "\\N")
        .replace("\n", "\\N")
        .replace("\r", "\\N")
    )


def _karaoke_text(seg: Segment) -> str:
    """Build the Dialogue text with per-word ``{\\k}`` tags.

    Word durations come from boundary differences so that the sum of all
    ``\\k`` durations exactly equals the Dialogue line duration in
    centiseconds (a libass expectation). Inter-word gaps are folded into the
    preceding word's duration (standard karaoke practice — the highlight
    holds until the next word starts), and any rounding remainder lands on
    the last word because its boundary is pinned to the segment end.
    """
    start_cs = _cs(seg.start)
    end_cs = _cs(seg.end)

    # Boundaries: segment start, each subsequent word's start, segment end.
    # Clamp to the segment window and force monotonicity so durations are
    # never negative even with slightly overlapping word timestamps.
    boundaries = [start_cs]
    for w in seg.words[1:]:
        b = max(boundaries[-1], min(_cs(w.start), end_cs))
        boundaries.append(b)
    boundaries.append(max(boundaries[-1], end_cs))

    parts: list[str] = []
    for i, w in enumerate(seg.words):
        dur = boundaries[i + 1] - boundaries[i]
        parts.append(f"{{\\k{dur}}}{_escape(w.word.strip())}")
    return " ".join(parts)


def export_ass(result: TranscriptionResult) -> str:
    """Return an ASS document with karaoke word highlighting per segment."""
    lines: list[str] = [_HEADER]
    for seg in result.segments:
        text = _karaoke_text(seg) if seg.words else _escape(seg.text.strip())
        lines.append(
            f"Dialogue: 0,{_fmt(seg.start)},{_fmt(seg.end)},Default,,0,0,0,,{text}"
        )
    return "\n".join(lines) + "\n"
