"""Tests for the ASS (karaoke) exporter."""

import re

import pytest

from backend.exporters.ass_export import export_ass
from backend.exporters.cue_split import MAX_LINES, split_segments
from backend.exporters.srt_standard import export_srt_standard
from backend.models.schemas import Segment, TranscriptionResult, WordSegment

HEADER = """[Script Info]
; Script generated by CapForge
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,72,&H00FFFFFF,&H002A95D4,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3,0,2,60,60,60,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

# "Crossing the hour" is one segment with an hour of silence inside it. It used
# to be one Dialogue whose "the" held a 366000 cs karaoke highlight; cues split
# it like SRT does. "the" is under the 1 s minimum, so its cue end is pushed
# into the silence and the word's \\k absorbs it (50 cs spoken → 100 cs).
GOLDEN = HEADER + """Dialogue: 0,0:00:00.00,0:00:02.50,Default,,0,0,0,,{\\k75}Hello {\\k75}brave {\\k100}world
Dialogue: 0,0:01:01.25,0:01:02.00,Default,,0,0,0,,{\\k75}Crossing
Dialogue: 0,0:01:02.00,0:01:03.00,Default,,0,0,0,,{\\k100}the
Dialogue: 0,1:02:02.00,1:02:03.50,Default,,0,0,0,,{\\k150}hour
"""

# Two WhisperX segments, four sentences (conftest ``multi_sentence_result``).
MULTI_SENTENCE_GOLDEN = HEADER + (
    "Dialogue: 0,0:00:00.50,0:00:02.03,Default,,0,0,0,,"
    "{\\k32}Welcome {\\k32}back {\\k32}to {\\k32}the {\\k25}channel.\n"
    "Dialogue: 0,0:00:02.10,0:00:06.51,Default,,0,0,0,,"
    "{\\k32}Today {\\k32}we {\\k32}are {\\k32}going {\\k32}to {\\k32}look {\\k32}at {\\k32}how"
    "\\N{\\k32}subtitles {\\k32}get {\\k32}split {\\k32}into {\\k32}readable {\\k25}cues,\n"
    "Dialogue: 0,0:00:06.58,0:00:10.67,Default,,0,0,0,,"
    "{\\k32}and {\\k32}why {\\k32}a {\\k32}single {\\k32}segment {\\k32}is {\\k32}never"
    "\\N{\\k32}the {\\k32}right {\\k32}unit {\\k32}for {\\k32}a {\\k25}caption.\n"
    "Dialogue: 0,0:00:14.00,0:00:14.32,Default,,0,0,0,,{\\k32}Okay.\n"
    "Dialogue: 0,0:00:14.32,0:00:17.77,Default,,0,0,0,,"
    "{\\k32}It {\\k32}matters {\\k32}more {\\k32}than {\\k32}you {\\k32}would"
    "\\N{\\k32}think, {\\k32}especially {\\k32}on {\\k32}a {\\k25}phone.\n"
)


def _ts_to_cs(ts: str) -> int:
    """Parse an ASS H:MM:SS.cc timestamp into centiseconds."""
    h, m, rest = ts.split(":")
    s, cs = rest.split(".")
    return ((int(h) * 60 + int(m)) * 60 + int(s)) * 100 + int(cs)


def _dialogue_lines(out: str) -> list[str]:
    return [l for l in out.splitlines() if l.startswith("Dialogue:")]


def _fields(line: str) -> tuple[int, int, str]:
    fields = line.split(",", 9)
    return _ts_to_cs(fields[1]), _ts_to_cs(fields[2]), fields[9]


def _visible_lines(text: str) -> list[str]:
    """The on-screen lines of a Dialogue: override blocks removed, split at \\N."""
    return re.sub(r"\{[^}]*\}", "", text).split("\\N")


def _k_sum(text: str) -> int:
    return sum(int(d) for d in re.findall(r"\\k(\d+)", text))


def _srt_seconds(stamp: str) -> float:
    hms, ms = stamp.split(",")
    h, m, s = (int(part) for part in hms.split(":"))
    return h * 3600 + m * 60 + s + int(ms) / 1000


def _plain_long_segment() -> Segment:
    text = (
        "The first sentence here is short. Then comes a much longer sentence that "
        "keeps on going well past what two subtitle lines could ever hold on screen. "
        "Done."
    )
    return Segment(start=0.0, end=20.0, text=text)


# --- Format ---------------------------------------------------------------

def test_golden_full_output(transcription_result):
    assert export_ass(transcription_result) == GOLDEN


def test_golden_multi_sentence_output(multi_sentence_result):
    assert export_ass(multi_sentence_result) == MULTI_SENTENCE_GOLDEN


def test_secondary_colour_is_brand_orange_bgr(transcription_result):
    # #D4952A in ASS &HAABBGGRR order (blue-first) — NOT &H00D4952A.
    out = export_ass(transcription_result)
    style_line = next(l for l in out.splitlines() if l.startswith("Style:"))
    assert "&H002A95D4" in style_line
    assert "&H00D4952A" not in out


def test_timestamp_centisecond_rounding():
    # 1.005 s → 100.4999… cs (float) → rounds to 100 cs; 1.006 s → 101 cs.
    result = TranscriptionResult(
        segments=[
            Segment(start=1.005, end=2.0, text="a"),
            Segment(start=1.006, end=2.999, text="b"),
        ]
    )
    lines = _dialogue_lines(export_ass(result))
    assert lines[0].split(",")[1] == "0:00:01.00"
    assert lines[1].split(",")[1] == "0:00:01.01"
    assert lines[1].split(",")[2] == "0:00:03.00"


def test_empty_result_has_header_but_no_dialogue(empty_result):
    out = export_ass(empty_result)
    assert out.startswith("[Script Info]")
    assert "[V4+ Styles]" in out
    assert "[Events]" in out
    assert not _dialogue_lines(out)


# --- Cue segmentation (the bug: one Dialogue per WhisperX segment) ----------

def test_a_multi_sentence_segment_becomes_several_dialogues(multi_sentence_result):
    lines = _dialogue_lines(export_ass(multi_sentence_result))
    # Two segments, four sentences, one of them long enough to split again.
    assert len(lines) == 5
    assert _visible_lines(_fields(lines[0])[2]) == ["Welcome back to the channel."]
    assert _visible_lines(_fields(lines[3])[2]) == ["Okay."]


def test_a_long_sentence_wraps_with_hard_breaks_and_splits_past_two_lines(
    multi_sentence_result,
):
    lines = _dialogue_lines(export_ass(multi_sentence_result))
    texts = [_fields(line)[2] for line in lines]
    # "Today … caption." is one sentence of four lines' worth: two Dialogues.
    assert _visible_lines(texts[1]) == [
        "Today we are going to look at how",
        "subtitles get split into readable cues,",
    ]
    assert _visible_lines(texts[2]) == [
        "and why a single segment is never",
        "the right unit for a caption.",
    ]
    for text in texts:
        assert text.count("\\N") <= MAX_LINES - 1
        assert "\n" not in text


@pytest.mark.parametrize("fixture", ["transcription_result", "multi_sentence_result"])
def test_dialogue_lines_match_the_srt_cue_lines(fixture, request):
    result = request.getfixturevalue(fixture)
    cues = split_segments(result.segments)
    lines = _dialogue_lines(export_ass(result))
    assert [_visible_lines(_fields(line)[2]) for line in lines] == [
        list(cue.lines) for cue in cues
    ]


# --- Timing parity with SRT -----------------------------------------------

@pytest.mark.parametrize("fixture", ["transcription_result", "multi_sentence_result"])
def test_dialogue_times_are_the_cue_times(fixture, request):
    result = request.getfixturevalue(fixture)
    cues = split_segments(result.segments)
    lines = _dialogue_lines(export_ass(result))
    assert len(lines) == len(cues)
    for line, cue in zip(lines, cues):
        start_cs, end_cs, _ = _fields(line)
        assert start_cs == round(cue.start * 100)
        assert end_cs == round(cue.end * 100)


def test_dialogue_times_agree_with_the_srt_export(multi_sentence_result):
    srt_blocks = [
        b for b in export_srt_standard(multi_sentence_result).split("\n\n") if b.strip()
    ]
    lines = _dialogue_lines(export_ass(multi_sentence_result))
    assert len(lines) == len(srt_blocks)
    for line, block in zip(lines, srt_blocks):
        srt_start, srt_end = (_srt_seconds(s) for s in block.splitlines()[1].split(" --> "))
        start_cs, end_cs, _ = _fields(line)
        # SRT truncates to ms, ASS rounds to cs: never more than one cs apart.
        assert abs(start_cs / 100 - srt_start) <= 0.01 + 1e-9
        assert abs(end_cs / 100 - srt_end) <= 0.01 + 1e-9


# --- Karaoke --------------------------------------------------------------

@pytest.mark.parametrize("fixture", ["transcription_result", "multi_sentence_result"])
def test_k_durations_sum_to_each_dialogue_duration(fixture, request):
    lines = _dialogue_lines(export_ass(request.getfixturevalue(fixture)))
    assert lines
    for line in lines:
        start_cs, end_cs, text = _fields(line)
        assert _k_sum(text) == end_cs - start_cs


def test_every_word_is_tagged_once_across_the_cues(multi_sentence_result):
    texts = [_fields(line)[2] for line in _dialogue_lines(export_ass(multi_sentence_result))]
    tagged = [w for text in texts for w in re.findall(r"\{\\k\d+\}([^\s{\\]+)", text)]
    expected = [w.word for seg in multi_sentence_result.segments for w in seg.words]
    assert tagged == expected


def test_the_hard_break_sits_between_tagged_words(multi_sentence_result):
    text = _fields(_dialogue_lines(export_ass(multi_sentence_result))[1])[2]
    assert "{\\k32}how\\N{\\k32}subtitles" in text
    assert " \\N" not in text and "\\N " not in text


def test_last_word_absorbs_a_minimum_duration_extension():
    words = [
        WordSegment(word="Hi.", start=0.0, end=0.2),
        WordSegment(word="Later", start=9.0, end=9.2),
        WordSegment(word="on.", start=9.3, end=9.5),
    ]
    seg = Segment(start=0.0, end=9.5, text="Hi. Later on.", words=words)
    lines = _dialogue_lines(export_ass(TranscriptionResult(segments=[seg])))
    # The cue end is pushed from 0.2 s to the 1.0 s readable minimum.
    assert lines[0] == "Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\\k100}Hi."
    assert lines[1].endswith(",{\\k30}Later {\\k20}on.")


def test_word_timings_are_never_shifted(multi_sentence_result):
    """Each inner \\k boundary is a word's own start — nothing is re-timed."""
    starts = {round(w.start * 100) for s in multi_sentence_result.segments for w in s.words}
    for line in _dialogue_lines(export_ass(multi_sentence_result)):
        start_cs, _, text = _fields(line)
        cursor = start_cs
        durations = [int(d) for d in re.findall(r"\\k(\d+)", text)]
        for duration in durations[:-1]:
            cursor += duration
            assert cursor in starts


def test_words_without_text_fold_into_their_neighbour():
    words = [
        WordSegment(word="Hello", start=0.0, end=0.5),
        WordSegment(word=" ", start=0.5, end=0.8),
        WordSegment(word="there", start=0.8, end=1.5),
    ]
    seg = Segment(start=0.0, end=1.5, text="Hello there", words=words)
    (line,) = _dialogue_lines(export_ass(TranscriptionResult(segments=[seg])))
    assert line.endswith(",{\\k80}Hello {\\k70}there")


# --- Degraded alignment ---------------------------------------------------

def test_segment_without_words_has_no_k_tags():
    result = TranscriptionResult(
        segments=[Segment(start=0.0, end=1.5, text="  plain text  ")]
    )
    out = export_ass(result)
    lines = _dialogue_lines(out)
    assert len(lines) == 1
    assert "\\k" not in lines[0]
    assert lines[0].endswith(",plain text")


def test_segment_without_words_is_still_split_into_cues():
    seg = _plain_long_segment()
    lines = _dialogue_lines(export_ass(TranscriptionResult(segments=[seg])))
    cues = split_segments([seg])
    assert len(lines) == len(cues) >= 3
    for line, cue in zip(lines, cues):
        start_cs, end_cs, text = _fields(line)
        assert "\\k" not in text
        assert text.split("\\N") == list(cue.lines)
        assert (start_cs, end_cs) == (round(cue.start * 100), round(cue.end * 100))
        assert 0 <= start_cs < end_cs <= 2000


# --- Escaping -------------------------------------------------------------

def test_braces_and_newlines_are_escaped():
    result = TranscriptionResult(
        segments=[
            Segment(
                start=0.0,
                end=1.5,
                text="{hi} there one two",
                words=[
                    WordSegment(word="{hi}", start=0.0, end=0.5),
                    WordSegment(word="there", start=0.5, end=1.0),
                    WordSegment(word="one\ntwo", start=1.0, end=1.5),
                ],
            ),
            Segment(start=2.0, end=3.0, text="{plain} words"),
        ]
    )
    lines = _dialogue_lines(export_ass(result))
    assert len(lines) == 2
    assert "{\\k50}(hi)" in lines[0]
    assert "{hi}" not in lines[0]
    assert "one\\Ntwo" in lines[0]
    assert "\n" not in lines[0]
    assert lines[1].endswith(",(plain) words")
