"""Tests for the ASS (karaoke) exporter."""

import re

from backend.exporters.ass_export import export_ass
from backend.models.schemas import Segment, TranscriptionResult, WordSegment

GOLDEN = """[Script Info]
; Script generated by CapForge
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,72,&H00FFFFFF,&H002A95D4,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3,0,2,60,60,60,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:02.50,Default,,0,0,0,,{\\k75}Hello {\\k75}brave {\\k100}world
Dialogue: 0,0:01:01.25,1:02:03.50,Default,,0,0,0,,{\\k75}Crossing {\\k366000}the {\\k150}hour
"""


def _ts_to_cs(ts: str) -> int:
    """Parse an ASS H:MM:SS.cc timestamp into centiseconds."""
    h, m, rest = ts.split(":")
    s, cs = rest.split(".")
    return ((int(h) * 60 + int(m)) * 60 + int(s)) * 100 + int(cs)


def _dialogue_lines(out: str) -> list[str]:
    return [l for l in out.splitlines() if l.startswith("Dialogue:")]


def test_golden_full_output(transcription_result):
    assert export_ass(transcription_result) == GOLDEN


def test_k_durations_sum_to_dialogue_duration(transcription_result):
    out = export_ass(transcription_result)
    lines = _dialogue_lines(out)
    assert len(lines) == 2
    for line in lines:
        fields = line.split(",", 9)
        start_cs = _ts_to_cs(fields[1])
        end_cs = _ts_to_cs(fields[2])
        text = fields[9]
        k_sum = sum(int(d) for d in re.findall(r"\\k(\d+)", text))
        assert k_sum == end_cs - start_cs


def test_secondary_colour_is_brand_orange_bgr(transcription_result):
    # #D4952A in ASS &HAABBGGRR order (blue-first) — NOT &H00D4952A.
    out = export_ass(transcription_result)
    style_line = next(l for l in out.splitlines() if l.startswith("Style:"))
    assert "&H002A95D4" in style_line
    assert "&H00D4952A" not in out


def test_timestamp_centisecond_rounding():
    # 1.005 s → 100.4999… cs (float) → rounds to 100 cs; 1.006 s → 101 cs.
    result = TranscriptionResult(
        segments=[
            Segment(start=1.005, end=2.0, text="a"),
            Segment(start=1.006, end=2.999, text="b"),
        ]
    )
    lines = _dialogue_lines(export_ass(result))
    assert lines[0].split(",")[1] == "0:00:01.00"
    assert lines[1].split(",")[1] == "0:00:01.01"
    assert lines[1].split(",")[2] == "0:00:03.00"


def test_segment_without_words_has_no_k_tags():
    result = TranscriptionResult(
        segments=[Segment(start=0.0, end=1.5, text="  plain text  ")]
    )
    out = export_ass(result)
    lines = _dialogue_lines(out)
    assert len(lines) == 1
    assert "\\k" not in lines[0]
    assert lines[0].endswith(",plain text")


def test_braces_and_newlines_are_escaped():
    result = TranscriptionResult(
        segments=[
            Segment(
                start=0.0,
                end=1.0,
                text="{hi} there",
                words=[
                    WordSegment(word="{hi}", start=0.0, end=0.5),
                    WordSegment(word="there", start=0.5, end=1.0),
                ],
            ),
            Segment(start=1.0, end=2.0, text="line one\nline two"),
        ]
    )
    out = export_ass(result)
    lines = _dialogue_lines(out)
    assert "(hi)" in lines[0]
    assert "{hi}" not in lines[0]
    assert "line one\\Nline two" in lines[1]


def test_empty_result_has_header_but_no_dialogue(empty_result):
    out = export_ass(empty_result)
    assert out.startswith("[Script Info]")
    assert "[V4+ Styles]" in out
    assert "[Events]" in out
    assert not _dialogue_lines(out)
