/**
 * The Canvas RSVP layout, checked against numbers the **Pillow reference actually
 * produced** — never against a second reading of its code.
 *
 * `__fixtures__/rsvp_canvas_parity.json` is generated by running
 * `backend/exporters/rsvp_layout.py` (`layout_line` + `caption_band`) through
 * `__fixtures__/gen_rsvp_canvas_parity.py`; see that generator's docstring for the
 * synthetic-font trick that makes the values reproducible in JS, and for the
 * follow-up that should also assert this fixture from the Python side.
 *
 * The other half of the contract — the reticle's EM geometry (mirroring
 * `backend/tests/test_rsvp_reticle.py`), the edge-fade ramp, the colour anchor and
 * the context dimming — is asserted below from the same constants Pillow uses.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, test } from 'vitest'
import {
  RETICLE_GAP_EM,
  RETICLE_NOTCH_LEN_EM,
  RETICLE_RULE_LEN_EM,
  RETICLE_THICKNESS_EM,
  computeRsvpPositions,
  computeRsvpReticleRects,
  computeWordPositions,
  measureTrackedWidth,
  rsvpCaptionBand,
  rsvpEdgeFadeAlpha,
  rsvpFadeGradientStops,
  rsvpPivotColumn,
  rsvpTrackingGap,
  rsvpWordAlpha,
  type CaptionBand,
  type RsvpFadeStop,
  type RsvpWordMetric,
} from './overlayGeometry'
import { focusSlices, lineOffsetAt, orpIndex } from './rsvp'

/** Digits of agreement required of a float comparison (tolerance 0.5e-9), the
 *  same bar the cross-language RSVP core fixtures use. */
const CLOSE_DIGITS = 9

// ── Fixture ──────────────────────────────────────────────────────

interface ParityExpectation {
  bandLeft: number
  bandWidth: number
  pivotPx: number
  wordWidths: number[]
  wordX: number[]
  focusOffsets: number[]
  lineX: number
  positions: number[]
  anchorIndex: number
  drawnFocusCenter: number
}

interface ParityCase {
  name: string
  tracking: number
  t: number
  expectedAnchorIndex: number
  midSlide?: { index: number; progress: number; eased: number }
  expected: ParityExpectation
}

interface AnchorCase {
  name: string
  words: Array<{ word: string; start: number; end: number }>
  t: number
  /** What `start <= t < end` would answer — carried so the case can be shown
   *  non-vacuous, i.e. that the two rules really do disagree here. */
  activeInWindow: number
  expected: ParityExpectation
}

interface ParityFixture {
  measure: { defaultCharWidth: number; charWidths: Record<string, number> }
  layout: {
    resolutionW: number
    maxWidth: number
    rowCenterX: number
    pivotFraction: number
    spaceW: number
    slideDuration: number
  }
  words: Array<{ word: string; widthScale: number; start: number; end: number; orpIndex: number }>
  vertical: {
    cy: number
    alignShiftY: number
    tyOff: number
    textH: number
    expectedRowCenterY: number
  }
  cases: ParityCase[]
  anchorCases: AnchorCase[]
}

/** Vitest runs from the repo root. */
const FIXTURE = JSON.parse(
  readFileSync(
    join(process.cwd(), 'src/renderer/src/lib/__fixtures__/rsvp_canvas_parity.json'),
    'utf8'
  )
) as ParityFixture

// Guard against a gutted fixture: every claim below is only as strong as the
// number of Pillow-generated cases it reads.
const MIN_PARITY_CASES = 14
const MIN_ANCHOR_CASES = 2

// ── The synthetic font, mirroring the generator's `SyntheticFont` ─

const { defaultCharWidth, charWidths } = FIXTURE.measure

/** `scale * sum(charWidths[c] for c in s)` — the Canvas twin of the generator's
 *  `SyntheticFont.getlength`, accumulated in the same left-to-right order. */
function measureText(scale: number, s: string): number {
  let total = 0
  for (const ch of Array.from(s)) total += charWidths[ch] ?? defaultCharWidth
  return scale * total
}

/** The renderer's real word-measurement primitive over the synthetic font. */
function measureWord(scale: number, text: string, tracking: number): number {
  return measureTrackedWidth(text, tracking, (s) => measureText(scale, s))
}

/**
 * Where the focus glyph's centre lands when the word is **drawn**.
 *
 * Re-derived from the hook's three-piece pen walk — `tracking` after *every*
 * character — and deliberately NOT from `measureTrackedWidth`, which counts
 * `n - 1` gaps. That is the point: if the layout drops the one missing gap
 * (`rsvpTrackingGap`), this number and the pivot part company by exactly one
 * `tracking`. Mirrors `drawn_focus_center` in the generator and in
 * `backend/tests/test_rsvp_layout.py`.
 */
function drawnFocusCenter(token: string, x: number, scale: number, tracking: number): number {
  const { prefix, focus } = focusSlices(token, orpIndex(token))
  let pen = x
  if (tracking === 0) {
    pen += measureText(scale, prefix)
  } else {
    for (const ch of Array.from(prefix)) pen += measureText(scale, ch) + tracking
  }
  return pen + measureText(scale, focus) / 2
}

interface SolveInput {
  words: Array<{ word: string; start: number; end: number; widthScale?: number }>
  tracking: number
  t: number
}

function solve({ words, tracking, t }: SolveInput) {
  const { resolutionW, maxWidth, rowCenterX, pivotFraction, spaceW, slideDuration } = FIXTURE.layout
  const scales = words.map((w) => w.widthScale ?? 1)
  const band = rsvpCaptionBand(resolutionW * maxWidth, rowCenterX)
  const pivotPx = rsvpPivotColumn(band, pivotFraction)
  const metrics: RsvpWordMetric[] = words.map((w, i) => ({
    word: w.word,
    width: measureWord(scales[i], w.word, tracking),
    start: w.start,
    end: w.end,
  }))

  const positions = computeRsvpPositions({
    words: metrics,
    measurePrefix: (index, text) => measureWord(scales[index], text, tracking),
    spaceW,
    tracking,
    pivotPx,
    slideDuration,
    currentTime: t,
    cy: FIXTURE.vertical.cy,
    alignShiftY: FIXTURE.vertical.alignShiftY,
    tyOff: FIXTURE.vertical.tyOff,
    totalTextH: FIXTURE.vertical.textH,
    textH: FIXTURE.vertical.textH,
  })
  return { band, pivotPx, metrics, positions, scales }
}

function expectClose(actual: readonly number[], expected: readonly number[], label: string): void {
  expect(actual.length, `${label}: length`).toBe(expected.length)
  actual.forEach((v, i) => expect(v, `${label}[${i}]`).toBeCloseTo(expected[i], CLOSE_DIGITS))
}

// ── 1. Numeric parity with the Pillow reference ──────────────────

describe('computeRsvpPositions vs the Pillow reference', () => {
  test('the fixture still carries every case the claims below need', () => {
    expect(FIXTURE.cases.length).toBeGreaterThanOrEqual(MIN_PARITY_CASES)
    expect(FIXTURE.anchorCases.length).toBeGreaterThanOrEqual(MIN_ANCHOR_CASES)
    // One word per ORP-table row, punctuation, and a font-size override: if
    // someone shortens a word here the sweep silently stops covering a row.
    expect(FIXTURE.words.map((w) => w.orpIndex)).toEqual([0, 1, 2, 3, 4, 3])
    expect(FIXTURE.words.map((w) => Array.from(w.word).length)).toEqual([1, 5, 9, 10, 15, 10])
    expect(FIXTURE.words.some((w) => w.widthScale !== 1)).toBe(true)
    expect(FIXTURE.cases.map((c) => c.tracking)).toContain(0)
    expect(FIXTURE.cases.some((c) => c.tracking !== 0)).toBe(true)
    expect(FIXTURE.cases.some((c) => c.midSlide)).toBe(true)
  })

  test.each(FIXTURE.cases.map((c) => [c.name, c] as const))('%s', (_name, kase) => {
    const { expected } = kase
    const { band, pivotPx, metrics, positions } = solve({
      words: FIXTURE.words,
      tracking: kase.tracking,
      t: kase.t,
    })

    // The band is `resolution_w * max_width` centred on the row anchor — not a
    // second width concept — and the pivot is a fraction of it.
    expect(band.left).toBeCloseTo(expected.bandLeft, CLOSE_DIGITS)
    expect(band.width).toBeCloseTo(expected.bandWidth, CLOSE_DIGITS)
    expect(pivotPx).toBeCloseTo(expected.pivotPx, CLOSE_DIGITS)

    // The measurement primitive itself: same widths as `_measure_tracked`.
    expectClose(
      metrics.map((m) => m.width),
      expected.wordWidths,
      'wordWidths'
    )
    expectClose(positions.wordX, expected.wordX, 'wordX')
    expectClose(positions.focusOffsets, expected.focusOffsets, 'focusOffsets')
    expect(positions.lineX).toBeCloseTo(expected.lineX, CLOSE_DIGITS)
    expectClose(positions.wordXPos, expected.positions, 'positions')
    expect(positions.anchorIndex).toBe(expected.anchorIndex)
    expect(positions.anchorIndex).toBe(kase.expectedAnchorIndex)

    // ...and the glyph really is drawn where the layout says: a pen walk that
    // counts n gaps (not n-1) lands on Pillow's own number.
    const anchor = positions.anchorIndex
    const center = drawnFocusCenter(
      FIXTURE.words[anchor].word,
      positions.wordXPos[anchor],
      FIXTURE.words[anchor].widthScale,
      kase.tracking
    )
    expect(center).toBeCloseTo(expected.drawnFocusCenter, CLOSE_DIGITS)
  })

  test('mid-hold, the focus glyph centre IS the pivot column', () => {
    const holds = FIXTURE.cases.filter((c) => !c.midSlide)
    expect(holds.length).toBeGreaterThanOrEqual(12)

    for (const kase of holds) {
      const { pivotPx, positions } = solve({
        words: FIXTURE.words,
        tracking: kase.tracking,
        t: kase.t,
      })
      const anchor = positions.anchorIndex
      const center = drawnFocusCenter(
        FIXTURE.words[anchor].word,
        positions.wordXPos[anchor],
        FIXTURE.words[anchor].widthScale,
        kase.tracking
      )
      expect(center, kase.name).toBeCloseTo(pivotPx, CLOSE_DIGITS)
    }
  })

  test('mid-slide the line sits on the shared quadratic ease-out, between the targets', () => {
    for (const kase of FIXTURE.cases.filter((c) => c.midSlide)) {
      const { index, eased } = kase.midSlide!
      const { pivotPx, positions } = solve({
        words: FIXTURE.words,
        tracking: kase.tracking,
        t: kase.t,
      })
      const previousTarget = pivotPx - positions.focusOffsets[index - 1]
      const target = pivotPx - positions.focusOffsets[index]

      expect(eased).toBeCloseTo(0.75, CLOSE_DIGITS) // 1-(1-0.5)^2, i.e. power1.out
      expect(positions.lineX, kase.name).toBeCloseTo(
        previousTarget + (target - previousTarget) * eased,
        CLOSE_DIGITS
      )
      expect(Math.min(previousTarget, target)).toBeLessThan(positions.lineX)
      expect(positions.lineX).toBeLessThan(Math.max(previousTarget, target))

      // ...and it is `lineOffsetAt`'s own answer, not a second easing.
      expect(positions.lineX).toBeCloseTo(
        lineOffsetAt(
          kase.t,
          FIXTURE.words,
          positions.focusOffsets,
          pivotPx,
          FIXTURE.layout.slideDuration
        ),
        CLOSE_DIGITS
      )

      // The focus glyph is therefore NOT yet on the pivot.
      const anchor = positions.anchorIndex
      const center = drawnFocusCenter(
        FIXTURE.words[anchor].word,
        positions.wordXPos[anchor],
        FIXTURE.words[anchor].widthScale,
        kase.tracking
      )
      expect(Math.abs(center - pivotPx)).toBeGreaterThan(1)
    }
  })

  test('the tracking gap is what the non-zero-tracking cases actually need', () => {
    // Premise of `rsvpTrackingGap`: a prefix measurement counts n-1 gaps while the
    // pen walk that draws it counts n, so the layout must add exactly one.
    const prefix = 'eli'
    const measured = measureWord(1, prefix, 7)
    let drawn = 0
    for (const ch of Array.from(prefix)) drawn += measureText(1, ch) + 7
    expect(drawn - measured).toBeCloseTo(7, CLOSE_DIGITS)
    expect(rsvpTrackingGap(prefix, 7)).toBe(7)
    expect(rsvpTrackingGap('', 7)).toBe(0)
    expect(rsvpTrackingGap(prefix, 0)).toBe(0)
  })
})

// ── 2. One colouring rule: the word the line is parked on ────────

describe('the colour anchor is lastStartedIndex, not start <= t < end', () => {
  test.each(FIXTURE.anchorCases.map((c) => [c.name, c] as const))(
    'a %s group colours the word on the pivot',
    (_name, kase) => {
      const { pivotPx, positions } = solve({ words: kase.words, tracking: 0, t: kase.t })

      // Premise: the two rules really do disagree here, so this is not vacuous.
      expect(kase.activeInWindow).toBeGreaterThanOrEqual(0)
      expect(kase.activeInWindow).not.toBe(kase.expected.anchorIndex)

      expect(positions.anchorIndex).toBe(kase.expected.anchorIndex)
      expectClose(positions.wordXPos, kase.expected.positions, 'positions')

      // The anchor word's focus glyph lands exactly where Pillow drew it...
      const anchor = positions.anchorIndex
      const anchorCenter = drawnFocusCenter(
        kase.words[anchor].word,
        positions.wordXPos[anchor],
        1,
        0
      )
      expect(anchorCenter).toBeCloseTo(kase.expected.drawnFocusCenter, CLOSE_DIGITS)
      // ...i.e. ON the pivot once the slide into it has finished. (The overlapping
      // case is sampled mid-slide on purpose, so it is still on its way there.)
      const settled = kase.t - kase.words[anchor].start >= FIXTURE.layout.slideDuration
      if (settled) expect(anchorCenter).toBeCloseTo(pivotPx, CLOSE_DIGITS)

      // ...and the `start <= t < end` word's glyph is nowhere near the pivot,
      // which is the whole error the wrong rule would ship: the reticle would mark
      // a column with no coloured glyph in it.
      const wrong = kase.activeInWindow
      const wrongCenter = drawnFocusCenter(kase.words[wrong].word, positions.wordXPos[wrong], 1, 0)
      expect(Math.abs(wrongCenter - pivotPx)).toBeGreaterThan(10)
      expect(Math.abs(anchorCenter - pivotPx)).toBeLessThan(Math.abs(wrongCenter - pivotPx))
    }
  )
})

// ── 3. One unwrapped row + the wrap path's vertical formula ───────

describe('the RSVP line is a single row', () => {
  const words: RsvpWordMetric[] = [
    { word: 'alpha', width: 50, start: 0, end: 1 },
    { word: 'bravo', width: 60, start: 1, end: 2 },
    { word: 'charlie', width: 70, start: 2, end: 3 },
    { word: 'delta', width: 80, start: 3, end: 4 },
    { word: 'echo', width: 40, start: 4, end: 5 },
  ]
  const layout = (currentTime: number) =>
    computeRsvpPositions({
      words,
      measurePrefix: (_i, text) => text.length * 10,
      spaceW: 5,
      tracking: 0,
      pivotPx: 500,
      slideDuration: 0,
      currentTime,
      cy: 900,
      alignShiftY: 0,
      tyOff: 0,
      totalTextH: 40,
      textH: 40,
    })

  test('every word shares one row centre, however many words there are', () => {
    const { wordYPos, rowCenterY } = layout(2.5)

    expect(new Set(wordYPos).size).toBe(1)
    expect(wordYPos).toEqual(words.map(() => rowCenterY))
  })

  test('x accumulates by width + spaceW, then the whole line is translated', () => {
    const { wordX, wordXPos, lineX } = layout(2.5)

    // 0, +50+5, +60+5, +70+5, +80+5
    expect(wordX).toEqual([0, 55, 120, 195, 280])
    expect(wordXPos).toEqual(wordX.map((v) => v + lineX))
  })

  test('the row centre is the wrap path formula with a single row', () => {
    const { cy, alignShiftY, tyOff, textH, expectedRowCenterY } = FIXTURE.vertical
    const { wordYPos, rowCenterY } = computeRsvpPositions({
      words,
      measurePrefix: (_i, text) => text.length * 10,
      spaceW: 5,
      tracking: 0,
      pivotPx: 500,
      slideDuration: 0,
      currentTime: 2.5,
      cy,
      alignShiftY,
      tyOff,
      totalTextH: textH,
      textH,
    })

    // Same number Pillow's `_draw_all_rows` computes for its single RSVP row.
    expect(rowCenterY).toBeCloseTo(expectedRowCenterY, CLOSE_DIGITS)
    // ...and identical to what the wrap path reports for one row of the same size,
    // so a per-word fontSizeScale stays centred on the line's midline.
    const wrap = computeWordPositions(
      [words],
      [500],
      660,
      cy,
      0,
      alignShiftY,
      0,
      tyOff,
      textH,
      textH,
      0,
      5
    )
    expect(wordYPos[0]).toBe(wrap.wordYPos[0])
  })

  test('an empty group yields no positions and parks the line on the pivot', () => {
    const empty = computeRsvpPositions({
      words: [],
      measurePrefix: () => 0,
      spaceW: 5,
      tracking: 0,
      pivotPx: 500,
      slideDuration: 0.06,
      currentTime: 1,
      cy: 900,
      alignShiftY: 0,
      tyOff: 0,
      totalTextH: 40,
      textH: 40,
    })

    expect(empty.wordXPos).toEqual([])
    expect(empty.lineX).toBe(500)
    expect(empty.anchorIndex).toBe(0)
  })
})

// ── 4. The pivot reticle ─────────────────────────────────────────
//
// Mirrors backend/tests/test_rsvp_reticle.py, which pins the *drawn* size of each
// box to its EM formula: Pillow fills a half-open box precisely so Canvas can use
// the constants unmodified.

describe('computeRsvpReticleRects', () => {
  const PIVOT = 200
  const CENTER_Y = 200

  test('the EM constants match rsvp_layout.py', () => {
    expect(RETICLE_RULE_LEN_EM).toBe(1.1)
    expect(RETICLE_THICKNESS_EM).toBe(0.055)
    expect(RETICLE_GAP_EM).toBe(0.32)
    expect(RETICLE_NOTCH_LEN_EM).toBe(0.2)
  })

  test('drawn size IS the EM formula at textH 60', () => {
    const textH = 60
    const thickness = textH * RETICLE_THICKNESS_EM // 3.3
    const ruleLen = textH * RETICLE_RULE_LEN_EM // 66
    const notch = textH * RETICLE_NOTCH_LEN_EM // 12
    expect([ruleLen, notch]).toEqual([66, 12])

    const [upperRule, lowerRule, upperNotch, lowerNotch] = computeRsvpReticleRects(
      PIVOT,
      CENTER_Y,
      textH
    )
    for (const rule of [upperRule, lowerRule]) {
      expect(rule.w).toBeCloseTo(ruleLen, CLOSE_DIGITS)
      expect(rule.h).toBeCloseTo(thickness, CLOSE_DIGITS)
      expect(rule.x + rule.w / 2).toBeCloseTo(PIVOT, CLOSE_DIGITS)
    }
    for (const n of [upperNotch, lowerNotch]) {
      expect(n.h).toBeCloseTo(notch, CLOSE_DIGITS)
      expect(n.w).toBeCloseTo(thickness, CLOSE_DIGITS)
      expect(n.x + n.w / 2).toBeCloseTo(PIVOT, CLOSE_DIGITS)
    }
  })

  test('rule and notch are exactly contiguous, above and below the text box', () => {
    const textH = 60
    const gap = textH * RETICLE_GAP_EM
    const [upperRule, lowerRule, upperNotch, lowerNotch] = computeRsvpReticleRects(
      PIVOT,
      CENTER_Y,
      textH
    )
    const top = CENTER_Y - textH / 2 - gap
    const bottom = CENTER_Y + textH / 2 + gap

    // The rules sit outside the text box by the EM clearance...
    expect(upperRule.y + upperRule.h).toBeCloseTo(top, CLOSE_DIGITS)
    expect(lowerRule.y).toBeCloseTo(bottom, CLOSE_DIGITS)
    // ...and each notch points back toward the text from that same edge, with no
    // overlap and no seam.
    expect(upperNotch.y).toBeCloseTo(upperRule.y + upperRule.h, CLOSE_DIGITS)
    expect(lowerNotch.y + lowerNotch.h).toBeCloseTo(lowerRule.y, CLOSE_DIGITS)
    // Symmetric about the line's centre.
    expect(CENTER_Y - upperRule.y).toBeCloseTo(lowerRule.y + lowerRule.h - CENTER_Y, CLOSE_DIGITS)
  })

  test('thickness is floored at one pixel (textH 9 puts the EM value at 0.495)', () => {
    const textH = 9
    expect(textH * RETICLE_THICKNESS_EM).toBeLessThan(1)

    const rects = computeRsvpReticleRects(PIVOT, CENTER_Y, textH)
    expect(rects[0].h).toBe(1)
    expect(rects[1].h).toBe(1)
    expect(rects[2].w).toBe(1)
  })

  test('scales with the font: every box is a multiple of textH', () => {
    const small = computeRsvpReticleRects(PIVOT, CENTER_Y, 40)
    const large = computeRsvpReticleRects(PIVOT, CENTER_Y, 80)

    expect(large[0].w).toBeCloseTo(small[0].w * 2, CLOSE_DIGITS)
    expect(large[2].h).toBeCloseTo(small[2].h * 2, CLOSE_DIGITS)
  })
})

// ── 5. The edge fade ─────────────────────────────────────────────

describe('the RSVP edge fade', () => {
  const band: CaptionBand = { left: 100, width: 400 }
  const FADE = 0.12

  /** Evaluate the gradient the hook builds, the way a canvas does: piecewise
   *  linear between stops, terminal stops extended beyond the band. */
  function gradientAlphaAt(stops: readonly RsvpFadeStop[], x: number): number {
    const p = (x - band.left) / band.width
    if (p <= stops[0][0]) return stops[0][1]
    for (let i = 1; i < stops.length; i++) {
      const [o0, a0] = stops[i - 1]
      const [o1, a1] = stops[i]
      if (p <= o1) return o1 === o0 ? a1 : a0 + ((a1 - a0) * (p - o0)) / (o1 - o0)
    }
    return stops[stops.length - 1][1]
  }

  test('is off — a clean no-op — at 0 or a degenerate band', () => {
    expect(rsvpFadeGradientStops(band, 0)).toBeNull()
    expect(rsvpFadeGradientStops(band, -0.5)).toBeNull()
    expect(rsvpFadeGradientStops({ left: 100, width: 0 }, FADE)).toBeNull()
    // ...and with no mask every column is fully opaque, including outside the band.
    expect(rsvpEdgeFadeAlpha(0, band, 0)).toBe(1)
    expect(rsvpEdgeFadeAlpha(250, band, 0)).toBe(1)
  })

  test('is a ramp, not a step: monotonic rise, symmetric, zero outside the band', () => {
    const fadePx = band.width * FADE
    const ramp = Array.from({ length: Math.floor(fadePx) }, (_, d) =>
      rsvpEdgeFadeAlpha(band.left + d + 0.5, band, FADE)
    )

    expect(ramp).toEqual([...ramp].sort((a, b) => a - b))
    expect(new Set(ramp.filter((a) => a > 0 && a < 1)).size).toBeGreaterThan(fadePx / 2)
    // Both ends carry the same ramp, mirrored about the band centre.
    for (let d = 0; d < Math.floor(fadePx); d++) {
      expect(rsvpEdgeFadeAlpha(band.left + d + 0.5, band, FADE)).toBeCloseTo(
        rsvpEdgeFadeAlpha(band.left + band.width - d - 0.5, band, FADE),
        CLOSE_DIGITS
      )
    }
    // Untouched core, zero outside.
    expect(rsvpEdgeFadeAlpha(band.left + band.width / 2, band, FADE)).toBe(1)
    expect(rsvpEdgeFadeAlpha(band.left - 1, band, FADE)).toBe(0)
    expect(rsvpEdgeFadeAlpha(band.left + band.width + 1, band, FADE)).toBe(0)
    expect(rsvpEdgeFadeAlpha(band.left, band, FADE)).toBe(0)
  })

  test('the gradient the hook paints reproduces the ramp formula', () => {
    const stops = rsvpFadeGradientStops(band, FADE)!
    expect(stops).toEqual([
      [0, 0],
      [FADE, 1],
      [1 - FADE, 1],
      [1, 0],
    ])

    for (let x = band.left - 20; x <= band.left + band.width + 20; x += 0.5) {
      expect(gradientAlphaAt(stops, x), `x=${x}`).toBeCloseTo(
        rsvpEdgeFadeAlpha(x, band, FADE),
        CLOSE_DIGITS
      )
    }
  })

  test('a 50% fade (the schema ceiling) meets at alpha 1 in the middle', () => {
    const stops = rsvpFadeGradientStops(band, 0.5)!

    expect(stops.map(([o]) => o)).toEqual([0, 0.5, 0.5, 1])
    expect(rsvpEdgeFadeAlpha(band.left + band.width / 2, band, 0.5)).toBe(1)
    expect(gradientAlphaAt(stops, band.left + band.width / 2)).toBe(1)
  })

  test('the pivot can legally sit inside the ramp, which is why the reticle is exempt', () => {
    // `rsvpPivotX` is ge=0, so this is reachable from the slider: the text there
    // genuinely dims (the band is a window) — the reticle must not, so the hook
    // draws it outside the masked composite. Its geometry never sees the fade.
    const pivot = rsvpPivotColumn(band, 0)
    expect(rsvpEdgeFadeAlpha(pivot, band, FADE)).toBe(0)
    expect(computeRsvpReticleRects(pivot, 200, 40)).toEqual(
      computeRsvpReticleRects(rsvpPivotColumn(band, 0), 200, 40)
    )
  })
})

// ── 6. Context dimming ───────────────────────────────────────────

describe('rsvpWordAlpha', () => {
  test('leaves the anchor word undimmed and dims every other word', () => {
    expect(rsvpWordAlpha(1, 0.75, true)).toBe(1)
    expect(rsvpWordAlpha(1, 0.75, false)).toBe(0.75)
  })

  test('multiplies through the group animation alpha', () => {
    expect(rsvpWordAlpha(0.5, 0.75, false)).toBeCloseTo(0.375, CLOSE_DIGITS)
    expect(rsvpWordAlpha(0.5, 0.75, true)).toBe(0.5)
  })

  test('a context opacity of 1 dims nothing', () => {
    expect(rsvpWordAlpha(1, 1, false)).toBe(1)
  })
})

// ── 7. Wrap mode is untouched ────────────────────────────────────

describe('computeWordPositions (wrap mode must stay byte-identical)', () => {
  test('single row, centred on cx with offsets and align slack', () => {
    const rows = [[{ width: 10 }, { width: 20 }]]

    const { wordXPos, wordYPos } = computeWordPositions(
      rows,
      [35],
      100,
      200,
      -20,
      10,
      7,
      -3,
      20,
      20,
      0,
      5
    )

    // wx = 100 + (-20) + 7 - 17.5 = 69.5, then + 10 + 5
    expect(wordXPos).toEqual([69.5, 84.5])
    // rowY = 200 + 10 + (-3) - 10 + 10 = 207
    expect(wordYPos).toEqual([207, 207])
  })

  test('three rows stack by textH + rowLineGap', () => {
    const rows = [[{ width: 10 }], [{ width: 30 }], [{ width: 50 }]]

    const { wordXPos, wordYPos } = computeWordPositions(
      rows,
      [10, 30, 50],
      500,
      1000,
      0,
      0,
      0,
      0,
      3 * 40 + 2 * 8,
      40,
      8,
      6
    )

    expect(wordXPos).toEqual([495, 485, 475])
    // rowY0 = 1000 - 136/2 + 20 = 952, then +48 per row
    expect(wordYPos).toEqual([952, 1000, 1048])
  })
})
